# Generated by Django 5.2.13 on 2026-04-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for calendar display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'olympiad_event_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('external_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendar_app.olympiadeventtype')),
            ],
            options={
                'db_table': 'olympiad_events',
                'ordering': ['start_date'],
            },
        ),
    ]
