# Generated by Django 5.2.13 on 2026-06-19 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiadevent',
            options={'ordering': ['start_date'], 'verbose_name': 'Событие календаря', 'verbose_name_plural': 'События календаря'},
        ),
        migrations.AlterModelOptions(
            name='olympiadeventtype',
            options={'ordering': ['name'], 'verbose_name': 'Тип события', 'verbose_name_plural': 'Типы событий'},
        ),
        migrations.AlterField(
            model_name='olympiadevent',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='olympiadevent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='olympiadevent',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendar_app.olympiadeventtype', verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='olympiadevent',
            name='external_url',
            field=models.URLField(blank=True, default='', verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='olympiadevent',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='olympiadevent',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='olympiadevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='olympiadeventtype',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color for calendar display', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='olympiadeventtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
