# Generated by Django 5.2.13 on 2026-06-15 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Дедлайн сдачи', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='in_bank',
            field=models.BooleanField(default=False, help_text='Показывать в банке задач'),
        ),
        migrations.AddField(
            model_name='problem',
            name='level',
            field=models.CharField(blank=True, choices=[('school', 'Школьный'), ('municipal', 'Муниципальный'), ('regional', 'Региональный'), ('final', 'Заключительный')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='Подробный разбор (markdown с LaTeX)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Источник, напр. «ВсОШ 2023»', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='homework.homework'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='homework.tag'),
        ),
    ]
