# Generated by Django 5.2.13 on 2026-06-19 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_block_options_alter_course_options_and_more'),
        ('homework', '0002_tag_homework_due_date_problem_in_bank_problem_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='problemattachment',
            options={'verbose_name': 'Вложение задачи', 'verbose_name_plural': 'Вложения задач'},
        ),
        migrations.AlterModelOptions(
            name='problemoption',
            options={'ordering': ['order'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Решение ученика', 'verbose_name_plural': 'Решения учеников'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Дедлайн сдачи', null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('choice_single', 'Один вариант'), ('choice_multiple', 'Несколько вариантов'), ('number', 'Числовой ответ'), ('formula', 'Формула')], max_length=20, verbose_name='Тип ответа'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='correct_answer',
            field=models.JSONField(blank=True, help_text='JSON with correct answer data', null=True, verbose_name='Правильный ответ (JSON)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.TextField(blank=True, default='', verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='homework.homework', verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='in_bank',
            field=models.BooleanField(default=False, help_text='Показывать в банке задач', verbose_name='В банке задач'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.CharField(blank=True, choices=[('school', 'Школьный'), ('municipal', 'Муниципальный'), ('regional', 'Региональный'), ('final', 'Заключительный')], default='', max_length=20, verbose_name='Этап олимпиады'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='max_score',
            field=models.IntegerField(default=1, verbose_name='Макс. балл'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='Подробный разбор (markdown с LaTeX)', verbose_name='Разбор'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Источник, напр. «ВсОШ 2023»', max_length=255, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(help_text='Условие задачи (markdown с LaTeX)', verbose_name='Условие'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems', to='homework.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='file',
            field=models.FileField(upload_to='problems/attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='problemattachment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.problem', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='problemoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='problemoption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный'),
        ),
        migrations.AlterField(
            model_name='problemoption',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='problemoption',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='homework.problem', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='problemoption',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='problemoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='admin_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий проверяющего'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='answer',
            field=models.JSONField(help_text='JSON with student answer', verbose_name='Ответ ученика (JSON)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_auto_checked',
            field=models.BooleanField(default=False, verbose_name='Автопроверка'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Верно'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.problem', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Слаг'),
        ),
    ]
