# Generated by Django 5.2.13 on 2026-06-15 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Теория'), ('practice', 'Практика'), ('hard', 'Сложные задачи'), ('test', 'Тест'), ('mock', 'Пробник')], default='theory', max_length=20),
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('notes', 'Конспект'), ('formulas', 'Формулы'), ('starmap', 'Карта звёздного неба'), ('problems', 'Подборка задач'), ('other', 'Другое')], default='notes', max_length=20)),
                ('file', models.FileField(upload_to='lessons/materials/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson')),
            ],
            options={
                'db_table': 'lesson_materials',
                'ordering': ['order'],
            },
        ),
    ]
