# Generated by Django 5.2.13 on 2026-06-15 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homework', '0002_tag_homework_due_date_problem_in_bank_problem_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockOlympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.CharField(blank=True, choices=[('school', 'Школьный'), ('municipal', 'Муниципальный'), ('regional', 'Региональный'), ('final', 'Заключительный')], default='', max_length=20)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Длительность тура в минутах')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mock_olympiads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(help_text='started_at + duration_minutes')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to=settings.AUTH_USER_MODEL)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='olympiads.mockolympiad')),
            ],
            options={
                'db_table': 'mock_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MockAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, default=None, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.problem')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='olympiads.mockattempt')),
            ],
            options={
                'db_table': 'mock_answers',
                'unique_together': {('attempt', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='MockProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_problems', to='olympiads.mockolympiad')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_links', to='homework.problem')),
            ],
            options={
                'db_table': 'mock_problems',
                'ordering': ['order'],
                'unique_together': {('mock', 'problem')},
            },
        ),
    ]
