# Generated by Django 5.2.13 on 2026-06-19 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_homework_options_alter_problem_options_and_more'),
        ('olympiads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mockanswer',
            options={'verbose_name': 'Ответ в попытке', 'verbose_name_plural': 'Ответы в попытках'},
        ),
        migrations.AlterModelOptions(
            name='mockattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
        migrations.AlterModelOptions(
            name='mockolympiad',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пробная олимпиада', 'verbose_name_plural': 'Пробные олимпиады'},
        ),
        migrations.AlterModelOptions(
            name='mockproblem',
            options={'ordering': ['order'], 'verbose_name': 'Задача пробника', 'verbose_name_plural': 'Задачи пробника'},
        ),
        migrations.AlterField(
            model_name='mockanswer',
            name='answer',
            field=models.JSONField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='mockanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='olympiads.mockattempt', verbose_name='Попытка'),
        ),
        migrations.AlterField(
            model_name='mockanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Верно'),
        ),
        migrations.AlterField(
            model_name='mockanswer',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.problem', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='mockanswer',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='mockanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='mockattempt',
            name='deadline',
            field=models.DateTimeField(help_text='started_at + duration_minutes', verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='mockattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='mockattempt',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='mockattempt',
            name='max_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. балл'),
        ),
        migrations.AlterField(
            model_name='mockattempt',
            name='mock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='olympiads.mockolympiad', verbose_name='Пробная олимпиада'),
        ),
        migrations.AlterField(
            model_name='mockattempt',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='mockattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начато'),
        ),
        migrations.AlterField(
            model_name='mockattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='mockolympiad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='mockolympiad',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mockolympiad',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Длительность тура в минутах', verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='mockolympiad',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='mockolympiad',
            name='level',
            field=models.CharField(blank=True, choices=[('school', 'Школьный'), ('municipal', 'Муниципальный'), ('regional', 'Региональный'), ('final', 'Заключительный')], default='', max_length=20, verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='mockolympiad',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mockolympiad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='mockproblem',
            name='mock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_problems', to='olympiads.mockolympiad', verbose_name='Пробная олимпиада'),
        ),
        migrations.AlterField(
            model_name='mockproblem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='mockproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_links', to='homework.problem', verbose_name='Задача'),
        ),
    ]
